-- MySQL Script generated by MySQL Workbench
-- Thu Sep  3 19:20:44 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Pizzeria` ;

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Menu` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Menu` (
  `codice` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`codice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Prodotto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Prodotto` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Prodotto` (
  `nome` VARCHAR(100) NOT NULL,
  `tipo` ENUM('pizza', 'bevanda') NOT NULL,
  `prezzo` DECIMAL(6,2) NOT NULL,
  `codice_menu` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nome`),
  INDEX `fk_menu_idx` (`codice_menu` ASC) VISIBLE,
  CONSTRAINT `fk_prodotto_menu`
    FOREIGN KEY (`codice_menu`)
    REFERENCES `Pizzeria`.`Menu` (`codice`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Comanda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Comanda` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Comanda` (
  `data` DATE NOT NULL,
  `numero` SMALLINT UNSIGNED NOT NULL,
  `stato` ENUM('aperta', 'completata') NOT NULL DEFAULT 'aperta',
  `conto` DECIMAL(8,2) NULL,
  PRIMARY KEY (`data`, `numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`IstanzaProdotto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`IstanzaProdotto` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`IstanzaProdotto` (
  `numero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `prezzo_applicato` DECIMAL(6,2) NOT NULL,
  `stato` ENUM('non pronta', 'pronta') NOT NULL DEFAULT 'non pronta',
  `nome_prodotto` VARCHAR(100) NOT NULL,
  `data_comanda` DATE NOT NULL,
  `numero_comanda` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_prodotto_idx` (`nome_prodotto` ASC) VISIBLE,
  INDEX `fk_comanda_idx` (`data_comanda` ASC, `numero_comanda` ASC) VISIBLE,
  INDEX `stato_prodotto_idx` (`stato` ASC, `nome_prodotto` ASC) VISIBLE,
  CONSTRAINT `fk_istanza_prodotto`
    FOREIGN KEY (`nome_prodotto`)
    REFERENCES `Pizzeria`.`Prodotto` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_istanza_comanda`
    FOREIGN KEY (`data_comanda` , `numero_comanda`)
    REFERENCES `Pizzeria`.`Comanda` (`data` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`OrdineDaAsporto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`OrdineDaAsporto` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`OrdineDaAsporto` (
  `data_comanda` DATE NOT NULL,
  `numero_comanda` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`data_comanda`, `numero_comanda`),
  CONSTRAINT `fk_asporto_comanda`
    FOREIGN KEY (`data_comanda` , `numero_comanda`)
    REFERENCES `Pizzeria`.`Comanda` (`data` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`OrdineInConsegna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`OrdineInConsegna` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`OrdineInConsegna` (
  `data_comanda` DATE NOT NULL,
  `numero_comanda` SMALLINT UNSIGNED NOT NULL,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `indirizzo` VARCHAR(255) NOT NULL,
  `recapito_telefonico` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`data_comanda`, `numero_comanda`),
  CONSTRAINT `fk_consegna_comanda`
    FOREIGN KEY (`data_comanda` , `numero_comanda`)
    REFERENCES `Pizzeria`.`Comanda` (`data` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Tavolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Tavolo` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Tavolo` (
  `numero` SMALLINT UNSIGNED NOT NULL,
  `stato` ENUM('libero', 'occupato') NOT NULL DEFAULT 'libero',
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Occupare`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Occupare` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Occupare` (
  `data_comanda` DATE NOT NULL,
  `numero_comanda` SMALLINT UNSIGNED NOT NULL,
  `numero_tavolo` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`data_comanda`, `numero_comanda`),
  UNIQUE INDEX `numero_tavolo_UNIQUE` (`numero_tavolo` ASC) VISIBLE,
  CONSTRAINT `fk_occupare_comanda`
    FOREIGN KEY (`data_comanda` , `numero_comanda`)
    REFERENCES `Pizzeria`.`Comanda` (`data` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_occupare_tavolo`
    FOREIGN KEY (`numero_tavolo`)
    REFERENCES `Pizzeria`.`Tavolo` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`User` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`User` (
  `username` VARCHAR(45) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `ruolo` ENUM('manager', 'cameriere', 'pizzaiolo', 'barman') NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;

USE `Pizzeria` ;

-- -----------------------------------------------------
-- Placeholder table for view `Pizzeria`.`EntrataGiornaliera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`EntrataGiornaliera` (`data` INT, `entrata_giornaliera` INT);

-- -----------------------------------------------------
-- Placeholder table for view `Pizzeria`.`EntrataMensile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`EntrataMensile` (`anno` INT, `mese` INT, `entrata_mensile` INT);

-- -----------------------------------------------------
-- procedure apri_comanda_tavolo
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`apri_comanda_tavolo`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `apri_comanda_tavolo` (
    IN p_numero_tavolo SMALLINT UNSIGNED,
    OUT p_data_comanda DATE,
    OUT p_numero_comanda SMALLINT UNSIGNED
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    START TRANSACTION;

    SET p_data_comanda = CURRENT_DATE();

    SELECT COALESCE(MAX(numero) + 1, 0)
    INTO p_numero_comanda
    FROM Comanda
    WHERE data = p_data_comanda;

    INSERT INTO Comanda (data, numero, stato, conto)
    VALUES (p_data_comanda, p_numero_comanda, 'aperta', NULL);

    INSERT INTO Occupare (data_comanda, numero_comanda, numero_tavolo)
    VALUES (p_data_comanda, p_numero_comanda, p_numero_tavolo);

    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure aggiungi_ordinazione
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`aggiungi_ordinazione`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `aggiungi_ordinazione` (
    IN p_data_comanda DATE,
    IN p_numero_comanda SMALLINT UNSIGNED,
    IN p_nome_prodotto VARCHAR(100)
)
BEGIN
    DECLARE v_stato_comanda VARCHAR(15);

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
    START TRANSACTION;

    SET v_stato_comanda = (
        SELECT stato
        FROM Comanda
        WHERE data = p_data_comanda AND numero = p_numero_comanda
    );

    IF v_stato_comanda = 'completata' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Non è possibile aggiungere prodotti a una comanda completata';
    END IF;

    INSERT INTO IstanzaProdotto (nome_prodotto, data_comanda, numero_comanda)
    VALUES (p_nome_prodotto, p_data_comanda, p_numero_comanda);

    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure pizze_da_preparare
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`pizze_da_preparare`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `pizze_da_preparare` ()
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		RESIGNAL;
	END;

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	SET TRANSACTION READ ONLY;
	START TRANSACTION;

	SELECT ip.numero, ip.nome_prodotto
    FROM IstanzaProdotto AS ip
    JOIN Prodotto AS p ON p.nome = ip.nome_prodotto
    WHERE ip.stato = 'non pronta' AND p.tipo = 'pizza'
    ORDER BY ip.numero;
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure bevande_da_preparare
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`bevande_da_preparare`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `bevande_da_preparare` ()
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		RESIGNAL;
	END;

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	SET TRANSACTION READ ONLY;
	START TRANSACTION;

	SELECT ip.numero, ip.nome_prodotto
    FROM IstanzaProdotto AS ip
    JOIN Prodotto AS p ON p.nome = ip.nome_prodotto
    WHERE ip.stato = 'non pronta' AND p.tipo = 'bevanda'
    ORDER BY ip.numero;
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure segna_pizza_pronta
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`segna_pizza_pronta`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `segna_pizza_pronta` (
    IN p_numero_istanza INT UNSIGNED
)
BEGIN
    UPDATE IstanzaProdotto AS ip
    JOIN Prodotto AS p ON p.nome = ip.nome_prodotto
    SET ip.stato = 'pronta'
    WHERE ip.numero = p_numero_istanza AND ip.stato = 'non pronta' AND p.tipo = 'pizza';
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure segna_bevanda_pronta
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`segna_bevanda_pronta`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `segna_bevanda_pronta` (
    IN p_numero_istanza INT UNSIGNED
)
BEGIN
    UPDATE IstanzaProdotto AS ip
    JOIN Prodotto AS p ON p.nome = ip.nome_prodotto
    SET ip.stato = 'pronta'
    WHERE ip.numero = p_numero_istanza AND ip.stato = 'non pronta' AND p.tipo = 'bevanda';
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure prodotti_pronti_tavoli
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`prodotti_pronti_tavoli`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `prodotti_pronti_tavoli` ()
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		RESIGNAL;
	END;
    
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	SET TRANSACTION READ ONLY;
	START TRANSACTION;

    SELECT ip.numero, ip.nome_prodotto, o.numero_tavolo
    FROM IstanzaProdotto AS ip
    JOIN Occupare AS o ON o.data_comanda = ip.data_comanda AND o.numero_comanda = ip.numero_comanda
    JOIN Comanda AS c ON c.data = ip.data_comanda AND c.numero = ip.numero_comanda
    WHERE ip.stato = 'pronta' AND c.stato = 'aperta'
    ORDER BY o.numero_tavolo, ip.numero;
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure completa_comanda
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`completa_comanda`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `completa_comanda` (
    IN p_data_comanda DATE,
    IN p_numero_comanda SMALLINT UNSIGNED
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    START TRANSACTION;

    UPDATE Comanda
    SET stato = 'completata'
    WHERE data = p_data_comanda AND numero = p_numero_comanda AND stato = 'aperta';

    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure genera_scontrino
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`genera_scontrino`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `genera_scontrino` (
    IN p_data_comanda DATE,
    IN p_numero_comanda SMALLINT UNSIGNED
)
BEGIN

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		RESIGNAL;
	END;
    
	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
	SET TRANSACTION READ ONLY;
	START TRANSACTION;

    SELECT ip.nome_prodotto, COUNT(*) AS quantita, ip.prezzo_applicato AS prezzo_unitario, SUM(ip.prezzo_applicato) AS subtotale
    FROM IstanzaProdotto AS ip
    JOIN Comanda AS c ON c.data = ip.data_comanda AND c.numero = ip.numero_comanda
    WHERE ip.data_comanda = p_data_comanda AND ip.numero_comanda = p_numero_comanda AND c.stato = 'completata'
    GROUP BY ip.nome_prodotto, ip.prezzo_applicato
    ORDER BY ip.nome_prodotto;

    SELECT conto AS totale
    FROM Comanda
    WHERE data = p_data_comanda AND numero = p_numero_comanda AND stato = 'completata';
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure entrata_giornaliera
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`entrata_giornaliera`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `entrata_giornaliera` (
	IN p_data DATE
)
BEGIN
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		RESIGNAL;
	END;

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	SET TRANSACTION READ ONLY;
	START TRANSACTION;

    SELECT data, entrata_giornaliera
    FROM EntrataGiornaliera
    WHERE data = p_data;
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure entrata_mensile
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`entrata_mensile`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `entrata_mensile` (
	IN p_anno_mese CHAR(7)
)
BEGIN

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		RESIGNAL;
	END;

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	SET TRANSACTION READ ONLY;
	START TRANSACTION;

    IF p_anno_mese IS NULL OR p_anno_mese NOT REGEXP '^[1-9][0-9]{3}-(0[1-9]|1[0-2])$' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Il periodo deve essere espresso nel formato YYYY-MM';
    END IF;
    
    SELECT anno, mese, entrata_mensile
    FROM EntrataMensile
    WHERE anno = CAST(LEFT(p_anno_mese, 4) AS UNSIGNED) AND mese = CAST(RIGHT(p_anno_mese, 2) AS UNSIGNED);
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure libera_tavolo
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`libera_tavolo`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `libera_tavolo` (
    IN p_numero_tavolo SMALLINT UNSIGNED
)
BEGIN
    DELETE FROM Occupare
    WHERE numero_tavolo = p_numero_tavolo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure registra_asporto
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`registra_asporto`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `registra_asporto` (
	OUT p_data_comanda DATE,
    OUT p_numero_comanda SMALLINT UNSIGNED
)
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
		ROLLBACK;
        RESIGNAL;
	END;
    
    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    START TRANSACTION;
    
    SET p_data_comanda = CURRENT_DATE();
    
    SELECT COALESCE(MAX(numero) + 1, 0)
    INTO p_numero_comanda
    FROM Comanda
    WHERE data = p_data_comanda;

    INSERT INTO Comanda (data, numero, stato, conto)
    VALUES (p_data_comanda, p_numero_comanda, 'aperta', NULL);

    INSERT INTO OrdineDaAsporto (data_comanda, numero_comanda)
    VALUES (p_data_comanda, p_numero_comanda);
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure registra_consegna
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`registra_consegna`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `registra_consegna` (
	IN p_nome_cliente VARCHAR(100),
    IN p_indirizzo VARCHAR(255),
    IN p_recapito_telefonico VARCHAR(20),
    OUT p_data_comanda DATE,
    OUT p_numero_comanda SMALLINT UNSIGNED
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    START TRANSACTION;

    SET p_data_comanda = CURRENT_DATE();
    
    SELECT COALESCE(MAX(numero) + 1, 0)
    INTO p_numero_comanda
    FROM Comanda
    WHERE data = p_data_comanda;
	
    INSERT INTO Comanda (data, numero, stato, conto)
    VALUES (p_data_comanda, p_numero_comanda, 'aperta', NULL);

    INSERT INTO OrdineInConsegna (data_comanda, numero_comanda, nome_cliente, indirizzo, recapito_telefonico)
    VALUES (p_data_comanda, p_numero_comanda, p_nome_cliente, p_indirizzo, p_recapito_telefonico);
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modifica_prezzo
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`modifica_prezzo`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `modifica_prezzo` (
    IN p_nome_prodotto VARCHAR(100),
    IN p_nuovo_prezzo DECIMAL(6,2)
)
BEGIN
    UPDATE Prodotto
    SET prezzo = p_nuovo_prezzo
    WHERE nome = p_nome_prodotto;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure crea_user
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`crea_user`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `crea_user` (
    IN p_username VARCHAR(45),
    IN p_password VARCHAR(100),
    IN p_ruolo VARCHAR(20)
)
BEGIN
    IF TRIM(p_username) = '' OR p_password = '' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT =
            'Username e password non possono essere vuoti';
    END IF;

    INSERT INTO `User` (username, password, ruolo)
    VALUES (p_username, MD5(p_password), p_ruolo);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure login
-- -----------------------------------------------------

USE `Pizzeria`;
DROP procedure IF EXISTS `Pizzeria`.`login`;

DELIMITER $$
USE `Pizzeria`$$
CREATE PROCEDURE `login` (
    IN p_username VARCHAR(45),
    IN p_password VARCHAR(100),
    OUT p_ruolo INT
)
BEGIN
    DECLARE v_ruolo ENUM(
        'manager',
        'cameriere',
        'pizzaiolo',
        'barman'
    );

    SELECT ruolo
    INTO v_ruolo
    FROM `User`
    WHERE username = p_username AND password = MD5(p_password);

    IF v_ruolo = 'manager' THEN
        SET p_ruolo = 1;
    ELSEIF v_ruolo = 'cameriere' THEN
        SET p_ruolo = 2;
    ELSEIF v_ruolo = 'pizzaiolo' THEN
        SET p_ruolo = 3;
    ELSEIF v_ruolo = 'barman' THEN
        SET p_ruolo = 4;
    ELSE
        SET p_ruolo = 5;
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `Pizzeria`.`EntrataGiornaliera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`EntrataGiornaliera`;
DROP VIEW IF EXISTS `Pizzeria`.`EntrataGiornaliera` ;
USE `Pizzeria`;
CREATE  OR REPLACE VIEW EntrataGiornaliera AS
SELECT data, SUM(conto) AS entrata_giornaliera
FROM Comanda
WHERE stato = 'completata'
GROUP BY data;

-- -----------------------------------------------------
-- View `Pizzeria`.`EntrataMensile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`EntrataMensile`;
DROP VIEW IF EXISTS `Pizzeria`.`EntrataMensile` ;
USE `Pizzeria`;
CREATE  OR REPLACE VIEW EntrataMensile AS
SELECT YEAR(data) AS anno, MONTH(data) AS mese, SUM(conto) AS entrata_mensile
FROM Comanda
WHERE stato = 'completata'
GROUP BY YEAR(data), MONTH(data);
USE `Pizzeria`;

DELIMITER $$

USE `Pizzeria`$$
DROP TRIGGER IF EXISTS `Pizzeria`.`trg_prodotto_bi_prezzo` $$
USE `Pizzeria`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Pizzeria`.`trg_prodotto_bi_prezzo` BEFORE INSERT ON `Prodotto` FOR EACH ROW
BEGIN
    IF NEW.prezzo <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Il prezzo del prodotto deve essere maggiore di zero';
    END IF;
END$$


USE `Pizzeria`$$
DROP TRIGGER IF EXISTS `Pizzeria`.`trg_prodotto_bu_prezzo` $$
USE `Pizzeria`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Pizzeria`.`trg_prodotto_bu_prezzo` BEFORE UPDATE ON `Prodotto` FOR EACH ROW
BEGIN
    IF NEW.prezzo <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Il prezzo del prodotto deve essere maggiore di zero';
    END IF;
END$$


USE `Pizzeria`$$
DROP TRIGGER IF EXISTS `Pizzeria`.`trg_comanda_bi_numero` $$
USE `Pizzeria`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Pizzeria`.`trg_comanda_bi_numero` BEFORE INSERT ON `Comanda` FOR EACH ROW
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM Comanda
        WHERE data = NEW.data
    ) AND NEW.numero <> 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'La prima comanda della giornata deve avere numero zero';
    END IF;
END$$


USE `Pizzeria`$$
DROP TRIGGER IF EXISTS `Pizzeria`.`trg_comanda_bu_conto` $$
USE `Pizzeria`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Pizzeria`.`trg_comanda_bu_conto` BEFORE UPDATE ON `Comanda` FOR EACH ROW
BEGIN
	DECLARE v_conto DECIMAL(8,2);

	IF OLD.stato = 'aperta' AND NEW.stato = 'completata' THEN
		IF NOT EXISTS (
			SELECT 1
			FROM IstanzaProdotto
			WHERE data_comanda = OLD.data AND numero_comanda = OLD.numero
		) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'Non è possibile completare una comanda senza prodotti';
		END IF;
	 
		IF EXISTS (
			SELECT 1
			FROM IstanzaProdotto
			WHERE data_comanda = OLD.data 
				AND numero_comanda = OLD.numero
				AND stato = 'non pronta'
		) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'La comanda contiene prodotti non ancora pronti';
		END IF;

		SELECT SUM(prezzo_applicato)
		INTO v_conto
		FROM IstanzaProdotto
		WHERE data_comanda = OLD.data AND numero_comanda = OLD.numero;
		
		SET NEW.conto = v_conto;
	END IF;
END$$


USE `Pizzeria`$$
DROP TRIGGER IF EXISTS `Pizzeria`.`trg_istanza_bi_prezzo` $$
USE `Pizzeria`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Pizzeria`.`trg_istanza_bi_prezzo` BEFORE INSERT ON `IstanzaProdotto` FOR EACH ROW
BEGIN
    SET NEW.prezzo_applicato = (
        SELECT prezzo
        FROM Prodotto
        WHERE nome = NEW.nome_prodotto
    );
END$$


USE `Pizzeria`$$
DROP TRIGGER IF EXISTS `Pizzeria`.`trg_asporto_bi_tavolo` $$
USE `Pizzeria`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Pizzeria`.`trg_asporto_bi_tavolo` BEFORE INSERT ON `OrdineDaAsporto` FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1
        FROM Occupare
        WHERE data_comanda = NEW.data_comanda AND numero_comanda = NEW.numero_comanda
    )
    OR EXISTS (
		SELECT 1
        FROM OrdineInConsegna
        WHERE data_comanda = NEW.data_comanda AND numero_comanda = NEW.numero_comanda
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'La comanda è già associata a un tavolo o a un ordine in consegna';
    END IF;
END$$


USE `Pizzeria`$$
DROP TRIGGER IF EXISTS `Pizzeria`.`trg_consegna_bi_tavolo` $$
USE `Pizzeria`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Pizzeria`.`trg_consegna_bi_tavolo` BEFORE INSERT ON `OrdineInConsegna` FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1
        FROM Occupare
        WHERE data_comanda = NEW.data_comanda AND numero_comanda = NEW.numero_comanda
    )
    OR EXISTS (
		SELECT 1
        FROM OrdineDaAsporto
		WHERE data_comanda = NEW.data_comanda AND numero_comanda = NEW.numero_comanda
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'La comanda è già associata a un tavolo o a un ordine da asporto';
    END IF;
END$$


USE `Pizzeria`$$
DROP TRIGGER IF EXISTS `Pizzeria`.`trg_occupare_bi_ordine` $$
USE `Pizzeria`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Pizzeria`.`trg_occupare_bi_ordine` BEFORE INSERT ON `Occupare` FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1
        FROM OrdineDaAsporto
        WHERE data_comanda = NEW.data_comanda AND numero_comanda = NEW.numero_comanda
    ) OR EXISTS (
        SELECT 1
        FROM OrdineInConsegna
        WHERE data_comanda = NEW.data_comanda AND numero_comanda = NEW.numero_comanda
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'La comanda è già associata a un ordine da asporto o a un ordine in consegna';
    END IF;
END$$


USE `Pizzeria`$$
DROP TRIGGER IF EXISTS `Pizzeria`.`trg_occupare_ai_tavolo` $$
USE `Pizzeria`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Pizzeria`.`trg_occupare_ai_tavolo` AFTER INSERT ON `Occupare` FOR EACH ROW
BEGIN
    UPDATE Tavolo
    SET stato = 'occupato'
    WHERE numero = NEW.numero_tavolo;
END$$


USE `Pizzeria`$$
DROP TRIGGER IF EXISTS `Pizzeria`.`trg_occupare_bd_comanda` $$
USE `Pizzeria`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Pizzeria`.`trg_occupare_bd_comanda` BEFORE DELETE ON `Occupare` FOR EACH ROW
BEGIN
    IF (
        SELECT stato
        FROM Comanda
        WHERE data = OLD.data_comanda AND numero = OLD.numero_comanda
    ) <> 'completata' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Il tavolo può essere liberato solo dopo il completamento della comanda';
    END IF;
END$$


USE `Pizzeria`$$
DROP TRIGGER IF EXISTS `Pizzeria`.`trg_occupare_ad_tavolo` $$
USE `Pizzeria`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Pizzeria`.`trg_occupare_ad_tavolo` AFTER DELETE ON `Occupare` FOR EACH ROW
BEGIN
    UPDATE Tavolo
    SET stato = 'libero'
    WHERE numero = OLD.numero_tavolo;
END$$


DELIMITER ;
SET SQL_MODE = '';
DROP USER IF EXISTS db_manager;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'db_manager' IDENTIFIED BY 'apc8ZrB2&o';

GRANT EXECUTE ON procedure `Pizzeria`.`crea_user` TO 'db_manager';
GRANT EXECUTE ON procedure `Pizzeria`.`aggiungi_ordinazione` TO 'db_manager';
GRANT EXECUTE ON procedure `Pizzeria`.`completa_comanda` TO 'db_manager';
GRANT EXECUTE ON procedure `Pizzeria`.`genera_scontrino` TO 'db_manager';
GRANT EXECUTE ON procedure `Pizzeria`.`entrata_giornaliera` TO 'db_manager';
GRANT EXECUTE ON procedure `Pizzeria`.`entrata_mensile` TO 'db_manager';
GRANT EXECUTE ON procedure `Pizzeria`.`registra_asporto` TO 'db_manager';
GRANT EXECUTE ON procedure `Pizzeria`.`registra_consegna` TO 'db_manager';
GRANT EXECUTE ON procedure `Pizzeria`.`modifica_prezzo` TO 'db_manager';
GRANT EXECUTE ON procedure `Pizzeria`.`libera_tavolo` TO 'db_manager';
SET SQL_MODE = '';
DROP USER IF EXISTS db_cameriere;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'db_cameriere' IDENTIFIED BY '9Nv&AijaBD';

GRANT EXECUTE ON procedure `Pizzeria`.`apri_comanda_tavolo` TO 'db_cameriere';
GRANT EXECUTE ON procedure `Pizzeria`.`aggiungi_ordinazione` TO 'db_cameriere';
GRANT EXECUTE ON procedure `Pizzeria`.`prodotti_pronti_tavoli` TO 'db_cameriere';
SET SQL_MODE = '';
DROP USER IF EXISTS db_pizzaiolo;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'db_pizzaiolo' IDENTIFIED BY 'U$$W&#im3H';

GRANT EXECUTE ON procedure `Pizzeria`.`pizze_da_preparare` TO 'db_pizzaiolo';
GRANT EXECUTE ON procedure `Pizzeria`.`segna_pizza_pronta` TO 'db_pizzaiolo';
SET SQL_MODE = '';
DROP USER IF EXISTS db_barman;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'db_barman' IDENTIFIED BY 'iD#2FZ3%dR';

GRANT EXECUTE ON procedure `Pizzeria`.`bevande_da_preparare` TO 'db_barman';
GRANT EXECUTE ON procedure `Pizzeria`.`segna_bevanda_pronta` TO 'db_barman';
SET SQL_MODE = '';
DROP USER IF EXISTS db_login;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'db_login' IDENTIFIED BY '5RNqNSm%VW';

GRANT EXECUTE ON procedure `Pizzeria`.`login` TO 'db_login';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Pizzeria`.`Menu`
-- -----------------------------------------------------
START TRANSACTION;
USE `Pizzeria`;
INSERT INTO `Pizzeria`.`Menu` (`codice`) VALUES (1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Pizzeria`.`Prodotto`
-- -----------------------------------------------------
START TRANSACTION;
USE `Pizzeria`;
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Margherita', 'pizza', 6.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Marinara', 'pizza', 5.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Napoli', 'pizza', 7.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Diavola', 'pizza', 8.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Capricciosa', 'pizza', 9.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Quattro Stagioni', 'pizza', 9.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Quattro Formaggi', 'pizza', 8.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Prosciutto e Funghi', 'pizza', 8.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Ortolana', 'pizza', 8.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Boscaiola', 'pizza', 9.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Bufalina', 'pizza', 8.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Romana', 'pizza', 7.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Siciliana', 'pizza', 8.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Tonno e Cipolla', 'pizza', 8.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Wurstel e Patatine', 'pizza', 8.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Parmigiana', 'pizza', 8.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Bresaola Rucola e Grana', 'pizza', 8.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Speck e Brie', 'pizza', 9.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Salsiccia e Friarielli', 'pizza', 9.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Vegetariana', 'pizza', 8.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Carbonara', 'pizza', 9.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Amatriciana', 'pizza', 9.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Pugliese', 'pizza', 7.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Bianca', 'pizza', 4.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Acqua Naturale', 'bevanda', 1.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Acqua Frizzante', 'bevanda', 1.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Coca Cola', 'bevanda', 3.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Coca Cola Zero', 'bevanda', 3.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Fanta', 'bevanda', 3.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Sprite', 'bevanda', 3.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Birra alla Spina Piccola', 'bevanda', 3.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Birra alla Spina Media', 'bevanda', 5.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Birra in Bottiglia', 'bevanda', 4.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Calice di Vino Bianco', 'bevanda', 4.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Calice di Vino Rosso', 'bevanda', 4.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Caffe Espresso', 'bevanda', 1.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Caffe Decaffeinato', 'bevanda', 1.50, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Spritz', 'bevanda', 6.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Sidro', 'bevanda', 4.00, 1);
INSERT INTO `Pizzeria`.`Prodotto` (`nome`, `tipo`, `prezzo`, `codice_menu`) VALUES ('Rossa', 'pizza', 5.00, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Pizzeria`.`Tavolo`
-- -----------------------------------------------------
START TRANSACTION;
USE `Pizzeria`;
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (1, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (2, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (3, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (4, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (5, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (6, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (7, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (8, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (9, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (10, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (11, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (12, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (13, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (14, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (15, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (16, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (17, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (18, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (19, 'libero');
INSERT INTO `Pizzeria`.`Tavolo` (`numero`, `stato`) VALUES (20, 'libero');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Pizzeria`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `Pizzeria`;
INSERT INTO `Pizzeria`.`User` (`username`, `password`, `ruolo`) VALUES ('d.sella', '68b6a57caa12f512ced21f89728fb89d', 'manager');

COMMIT;

