CONNECTION_URL=jdbc:mysql://localhost:3306/Pizzeria

LOGIN_USER=db_login
LOGIN_PASS=5RNqNSm%VW

MANAGER_USER=db_manager
MANAGER_PASS=apc8ZrB2&o

CAMERIERE_USER=db_cameriere
CAMERIERE_PASS=9Nv&AijaBD

PIZZAIOLO_USER=db_pizzaiolo
PIZZAIOLO_PASS=U$$W&#im3H

BARMAN_USER=db_barman
BARMAN_PASS=iD#2FZ3%dR